### ISSUE TITLE
Make icons configurable

### ISSUE THREAD

**Issue by madc** [Frontwise/grid-editor#9]
It would be great, if we could find a way, to make the icons configurable.
Many administration interfaces use Font Awesome and also personally I prefer it over Glyhicons. The only way to fix this now, is to edit the source code directly, what makes updating way less funnier.

I have no solution to propose yet, but wanted to put this in here for discussion.

A similar issue could also be about allowing grid frameworks other than bootstrap.

**Comment by Epskampie** [comment]
Yeah, good suggestion. I would prefer a solution that uses CSS, as it is clearly presentation. However, due to the way these font-icons work, this might be hard to realise.

A different solution might be along the lines of theme objects, which specify things like colors, icons etc.

BTW, the reason it just supports standard bootstrap (grid systems) at this point is to keep the scope narrow and the code simple.

**Comment by madc** [comment]
Maybe it could be a similar concept like you implemented the extensible RTEs? Something like `$.fn.gridEditor.framework.bootstrap`.

**Comment by Epskampie** [comment]
I've thought on this one, and decided it's not worth the effort / added complexity. The reason is that someone who want's to use the bootstrap grid will most likely have the full bootstrap included, and the glyphicons look pretty close to the font-awesome ones as not to be an eyesore. 

Same goes for allowing different grid systems, the whole reason bootstrap works so well is (in my opinion) that is sets a standard, and sticks to it, instead of making a million things possible. I want to follow the same philosophy for the plugin, and fight feature creep. So we will stick to strictly bootstrap.

Thanks for the suggestion nonetheless! :-)

**Comment by madc** [comment]
I respect your point of view and also don't care much for other grid systems.

As for the icons, I've to disagree. To me, the main purpose of this plugin it the integration into existing systems. I already included it as a module into [Prestashop](https://www.prestashop.com/) and currently work on extensions for [Bolt CMS](http://bolt.cm) and [Thelia e-commerce](http://thelia.net/). Bolt and Prestashop use font awesome and thelia use their own icon font. None of them has glyphicons installed.

But its not the end of the world. As for now i'll just modify the core code.

**Comment by Epskampie** [comment]
Hi madc,

I was thinking about this, isn't it possible to use some css to use the fontawesome icons? Something like this (not tested):

```css
.ge-canvas .glyphicon {
    /* Copied from font-awesome.css */
    display: inline-block;
    font: normal normal normal 14px/1 FontAwesome;
    font-size: inherit;
    text-rendering: auto;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
}

.ge-canvas .glyphicon-trash {
    /* Copied from font-awesome.css */
    content: "\f1f8";
}
```

This is a solution that uses css, so you wouldn't have to change the source. :) Would love a PR if you choose to implement this. It would be an extra css file that you could optionally include to use fontawesome.
